layout_spectrum: 0.2590676016049773
typography_spectrum: 0.16150787860321084
color:
  brandStrength: 0.7198943022254964
  lightness: 0.8155169707583725
  saturation: 0.627000423347725
  rhythmicContrast: 0.9471884489267842
  brandColors:
    - '#C8925B'
    - '#B67334'
    - '#0B0B0B'
    - '#CCC4BC'
    - '#754C24'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: coffee & dreams
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4b2ebdcd-f1c1-40f5-822a-f9ecd8b85680.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4b2ebdcd-f1c1-40f5-822a-f9ecd8b85680.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a2c98490-a24f-4b63-b5d1-67fdf145f069.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c0cff5a5-47da-41e5-aee6-ff2523d465e5.png
title: coffee & dreams
description: ''
url: 'https://thegrid.ai/coffeedreams/'
